# Generated by Django 3.2.7 on 2023-09-03 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("enquiries", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="enquiry",
            old_name="subjects",
            new_name="subject",
        ),
    ]
