# Generated by Django 3.2.7 on 2023-09-02 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0002_property_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="total_floors",
            field=models.IntegerField(default=1, verbose_name="Number of Floors"),
        ),
    ]
